Resources:
  ScraperRole1944D0E8:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonDynamoDBFullAccess
    Metadata:
      aws:cdk:path: FundPriceMonitorBackendStack/ScraperRole/Resource
  scrapeManulifeMPFPerformance9F5A8B56:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8S3Bucket06131B1A
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8S3VersionKey5CC93CD8
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8S3VersionKey5CC93CD8
      Handler: scrapeManulifeMPFPerformance.handler
      Role:
        Fn::GetAtt:
          - ScraperRole1944D0E8
          - Arn
      Runtime: nodejs12.x
      MemorySize: 700
      Timeout: 300
    DependsOn:
      - ScraperRole1944D0E8
    Metadata:
      aws:cdk:path: FundPriceMonitorBackendStack/scrapeManulifeMPFPerformance/Resource
      aws:asset:path: /Users/michaelchan/SANDBOX/michchan/fund-price-monitor-backend/bundles/cron/handlers
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.59.0,@aws-cdk/assets=1.59.0,@aws-cdk/aws-applicationautoscaling=1.59.0,@aws-cdk/aws-autoscaling-common=1.59.0,@aws-cdk/aws-cloudwatch=1.59.0,@aws-cdk/aws-codeguruprofiler=1.59.0,@aws-cdk/aws-ec2=1.59.0,@aws-cdk/aws-events=1.59.0,@aws-cdk/aws-iam=1.59.0,@aws-cdk/aws-kms=1.59.0,@aws-cdk/aws-lambda=1.59.0,@aws-cdk/aws-logs=1.59.0,@aws-cdk/aws-s3=1.59.0,@aws-cdk/aws-s3-assets=1.59.0,@aws-cdk/aws-sqs=1.59.0,@aws-cdk/aws-ssm=1.59.0,@aws-cdk/cloud-assembly-schema=1.59.0,@aws-cdk/core=1.59.0,@aws-cdk/cx-api=1.59.0,@aws-cdk/region-info=1.59.0,jsii-runtime=node.js/v10.16.2
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8S3Bucket06131B1A:
    Type: String
    Description: S3 bucket for asset "07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8"
  AssetParameters07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8S3VersionKey5CC93CD8:
    Type: String
    Description: S3 key for asset version "07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8"
  AssetParameters07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8ArtifactHash493B9CAA:
    Type: String
    Description: Artifact hash for asset "07b17d36a5b8c16f69a68faf34d2841010de30ebc0cdf6d1759bc388814e43a8"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

