# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push new tag.
on:
  push:
    tags: 
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      # For AWS construct
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      API_KEY: ${{ secrets.API_KEY }}
      GENERAL_LOG_SUBSCRIPTION_EMAIL: ${{ secrets.GENERAL_LOG_SUBSCRIPTION_EMAIL }}
      TELEGRAM_BOT_API_KEY_PARAMETER_NAME: ${{ secrets.TELEGRAM_BOT_API_KEY_PARAMETER_NAME }}
      TELEGRAM_CHAT_ID_PARAMETER_NAME: ${{ secrets.TELEGRAM_CHAT_ID_PARAMETER_NAME }}
      TELEGRAM_TEST_CHAT_ID_PARAMETER_NAME: ${{ secrets.TELEGRAM_TEST_CHAT_ID_PARAMETER_NAME }}
      # For runtime (passed by AWS construct)
      AWS_RUNTIME_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      API_CORS_WHITELIST: ${{ secrets.API_CORS_WHITELIST }}
      DEPLOYMENT_GITHUB_ACCESS_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_ACCESS_TOKEN }}
      DEPLOYMENT_GITHUB_OWNER: ${{ secrets.DEPLOYMENT_GITHUB_OWNER }}
      DEPLOYMENT_GITHUB_REPO: ${{ secrets.DEPLOYMENT_GITHUB_REPO }}
      DEPLOYMENT_GITHUB_WORKFLOW_ID: ${{ secrets.DEPLOYMENT_GITHUB_WORKFLOW_ID }}
      DEPLOYMENT_GITHUB_WORKFLOW_REF: ${{ secrets.DEPLOYMENT_GITHUB_WORKFLOW_REF }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout master branch
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      # Setup node
      - name: Setup Node with the right version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      # Yarn install
      - run: yarn install --frozen-lockfile

      # Run eslint test
      - name: Run ESLint test
        run: yarn run eslint

      # Clear last build cache
      - name: Clear last build cache
        run: yarn run clear-build-cache

      # Build
      - name: Build
        run: yarn run build

      # CDK Deploy 
      - name: cdk deploy
        run: yarn run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}