# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out from Git
        uses: actions/checkout@v2

      # Setup node
      - name: Setup Node with the right version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # NPM install
      - run: npm install

      # Run eslint test
      - name: Run ESLint test
        run: npm run eslintTest

      # Clear last build cache
      - name: Clear last build cache
        run: npm run clearbuildcache

      # Build
      - name: Build
        run: npm run build

      # CDK Deploy 
      - name: cdk deploy
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-east-1'
          TELEGRAM_BOT_API_KEY_PARAMETER_NAME: ${{ secrets.TELEGRAM_BOT_API_KEY_PARAMETER_NAME }}
          TELEGRAM_BOT_API_KEY_PARAMETER_VERSION: 1
          TELEGRAM_CHAT_ID_PARAMETER_NAME: ${{ secrets.TELEGRAM_CHAT_ID_PARAMETER_NAME }}
          LAMBDA_ERROR_LOG_SUBSCRIPTION_EMAIL: ${{ secrets.LAMBDA_ERROR_LOG_SUBSCRIPTION_EMAIL }}
          
      

